"""fix routing

Revision ID: 18e53e72c385
Revises: ea249d496934
Create Date: 2019-11-03 17:07:45.959698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e53e72c385'
down_revision = 'ea249d496934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('origin_text_box_id_fkey', 'routing', type_='foreignkey')
    op.drop_constraint('destination_text_box_id_fkey', 'routing', type_='foreignkey')
    op.drop_column('routing', 'origin_text_box_history_id')
    op.drop_column('routing', 'destination_text_box_history_id')

    op.create_table('routing_destination',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('routing_id', sa.Integer(), nullable=False),
        sa.Column('text_with_suggestion_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['routing_id'], ['routing.id'], ),
        sa.ForeignKeyConstraint(['text_with_suggestion_id'], ['text_with_suggestions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_origin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('routing_id', sa.Integer(), nullable=False),
        sa.Column('text_with_suggestion_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['routing_id'], ['routing.id'], ),
        sa.ForeignKeyConstraint(['text_with_suggestion_id'], ['text_with_suggestions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing', sa.Column('destination_text_box_history_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routing', sa.Column('origin_text_box_history_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('destination_text_box_id_fkey', 'routing', 'text_with_suggestions', ['destination_text_box_history_id'], ['id'])
    op.create_foreign_key('origin_text_box_id_fkey', 'routing', 'text_with_suggestions', ['origin_text_box_history_id'], ['id'])

    op.drop_table('routing_origin')
    op.drop_table('routing_destination')
    # ### end Alembic commands ###
