"""combine_tables

Revision ID: 2195e3e2a9ce
Revises: ed6021c67b9f
Create Date: 2019-10-31 10:40:36.829434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = '2195e3e2a9ce'
down_revision = 'ed6021c67b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_with_suggestions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('map_search_id', sa.Integer(), nullable=True),
                    sa.Column('text_typed', sa.Text(), nullable=False),
                    sa.Column('suggestion_choosen', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['map_search_id'], ['map_search.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('click_bbox_id_fkey', 'click', type_='foreignkey')
    op.drop_constraint('pan_new_bbox_id_fkey', 'pan', type_='foreignkey')
    op.drop_constraint('pan_old_bbox_id_fkey', 'pan', type_='foreignkey')
    op.drop_constraint('zoom_in_out_new_bbox_id_fkey', 'zoom_in_out', type_='foreignkey')
    op.drop_constraint('zoom_in_out_old_bbox_id_fkey', 'zoom_in_out', type_='foreignkey')
    op.drop_constraint('suggestions_text_with_suggestion_id_fkey', 'suggestions', type_='foreignkey')
    op.drop_constraint('zoom_in_out_map_interaction_type_id_fkey', 'zoom_in_out', type_='foreignkey')
    op.drop_constraint('spatial_bookmark_geocoord_id_fkey', 'spatial_bookmark', type_='foreignkey')
    op.drop_constraint('user_position_geocoord_id_fkey', 'user_position', type_='foreignkey')
    # op.drop_constraint('map_interaction_geocoord_id_fkey', 'map_interaction', type_='foreignkey')

    op.drop_constraint('map_search_bbox_id_fkey', 'map_search', type_='foreignkey')
    op.drop_column('map_search', 'bbox_id')
    # op.add_column('routing', sa.Column('end_routing_interface_send_request_or_interface_closed_time_stamp', sa.DateTime(), nullable=False))
    op.drop_constraint('routing_origin_text_box_history_id_fkey', 'routing', type_='foreignkey')
    op.drop_constraint('routing_destination_text_box_history_id_fkey', 'routing', type_='foreignkey')
    # op.create_foreign_key('origin_text_bbox_fk', 'routing', 'text_with_suggestions', ['origin_text_box_history_id'], ['id'])
    # op.create_foreign_key('dest_text_bbox_fk', 'routing', 'text_with_suggestions', ['destination_text_box_history_id'], ['id'])
    # op.drop_column('routing', 'end_routing_interface_send_request_or_interface_closed_time_sta')
    op.drop_table('text_with_suggestion')
    op.drop_table('bbox')
    op.drop_table('pan')
    op.drop_table('click')
    op.drop_table('zoom_in_out')
    op.drop_constraint('map_interaction_geocoord_id_fkey', 'map_interaction', type_='foreignkey')
    op.drop_column('map_interaction', 'geocoord_id')
    op.drop_index('idx_geocoordinate_with_time_stamp_geom', table_name='geocoordinate_with_time_stamp')
    op.drop_table('geocoordinate_with_time_stamp')
    op.drop_table('map_interaction_type')
    op.add_column('map_interaction', sa.Column('click_time_stamp', sa.DateTime()))
    op.add_column('map_interaction', sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), nullable=False))
    op.add_column('map_interaction', sa.Column('is_click_interaction', sa.Boolean(), nullable=True))
    op.add_column('map_interaction', sa.Column('is_pan_interaction', sa.Boolean(), nullable=True))
    op.add_column('map_interaction', sa.Column('is_zoom_in_interaction', sa.Boolean(), nullable=True))
    op.add_column('map_interaction', sa.Column('is_zoom_out_interaction', sa.Boolean(), nullable=True))
    op.add_column('map_interaction', sa.Column('new_bbox_geom', Geometry(geometry_type='POLYGON', srid=4326)))
    op.add_column('map_interaction', sa.Column('new_bbox_time_stamp', sa.DateTime()))
    op.add_column('map_interaction', sa.Column('new_zoom_level', sa.Integer()))
    op.add_column('map_interaction', sa.Column('old_bbox_geom', Geometry(geometry_type='POLYGON', srid=4326)))
    op.add_column('map_interaction', sa.Column('old_bbox_time_stamp', sa.DateTime()))
    op.add_column('map_interaction', sa.Column('old_zoom_level', sa.Integer()))
    op.add_column('map_interaction', sa.Column('time_stamp', sa.DateTime(), nullable=False))
    op.add_column('map_interaction', sa.Column('where_clicked_geom', Geometry(geometry_type='POINT', srid=4326)))
    op.add_column('map_search', sa.Column('bbox_geom', Geometry(geometry_type='POLYGON', srid=4326), nullable=False))
    op.add_column('map_search', sa.Column('bbox_time_stamp', sa.DateTime(), nullable=False))
    op.add_column('spatial_bookmark', sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), nullable=False))
    op.add_column('spatial_bookmark', sa.Column('time_stamp', sa.DateTime(), nullable=False))
    # op.drop_constraint('spatial_bookmark_geocoord_id_fkey', 'spatial_bookmark', type_='foreignkey')
    op.drop_column('spatial_bookmark', 'geocoord_id')
    op.add_column('suggestions', sa.Column('text_with_suggestions_id', sa.Integer(), nullable=True))
    # op.drop_constraint('suggestions_text_with_suggestion_id_fkey', 'suggestions', type_='foreignkey')
    op.create_foreign_key('text_with_suggestion_fk', 'suggestions', 'text_with_suggestions', ['text_with_suggestions_id'], ['id'])
    op.drop_column('suggestions', 'text_with_suggestion_id')
    op.add_column('user_position', sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), nullable=False))
    op.add_column('user_position', sa.Column('time_stamp', sa.DateTime(), nullable=False))
    # op.drop_constraint('user_position_geocoord_id_fkey', 'user_position', type_='foreignkey')
    op.drop_column('user_position', 'geocoord_id')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoordinate_with_time_stamp',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('geocoordinate_with_time_stamp_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='geocoordinate_with_time_stamp_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('bbox',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('upper_left_coordinate_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('lower_right_coordinate_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['lower_right_coordinate_id'], ['geocoordinate_with_time_stamp.id'], name='bbox_lower_right_coordinate_id_fkey'),
                    sa.ForeignKeyConstraint(['upper_left_coordinate_id'], ['geocoordinate_with_time_stamp.id'], name='bbox_upper_left_coordinate_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='bbox_pkey')
                    )
    op.create_table('map_interaction_type',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('map_interaction_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('map_interaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['map_interaction_id'], ['map_interaction.id'], name='map_interaction_type_map_interaction_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='map_interaction_type_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('zoom_in_out',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('map_interaction_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('old_zoom_level', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('new_zoom_level', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('old_bbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('new_bbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], name='zoom_in_out_map_interaction_type_id_fkey'),
                    sa.ForeignKeyConstraint(['new_bbox_id'], ['bbox.id'], name='zoom_in_out_new_bbox_id_fkey'),
                    sa.ForeignKeyConstraint(['old_bbox_id'], ['bbox.id'], name='zoom_in_out_old_bbox_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='zoom_in_out_pkey')
                    )
    op.create_table('text_with_suggestion',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('map_search_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('text_typed', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('suggestion_choosen', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['map_search_id'], ['map_search.id'], name='text_with_suggestion_map_search_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='text_with_suggestion_pkey')
                    )
    op.create_table('click',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('map_interaction_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('where_clicked_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('bbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['bbox_id'], ['bbox.id'], name='click_bbox_id_fkey'),
                    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], name='click_map_interaction_type_id_fkey'),
                    sa.ForeignKeyConstraint(['where_clicked_id'], ['geocoordinate_with_time_stamp.id'], name='click_where_clicked_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='click_pkey')
                    )
    op.create_table('pan',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('map_interaction_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('old_bbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('new_bbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], name='pan_map_interaction_type_id_fkey'),
                    sa.ForeignKeyConstraint(['new_bbox_id'], ['bbox.id'], name='pan_new_bbox_id_fkey'),
                    sa.ForeignKeyConstraint(['old_bbox_id'], ['bbox.id'], name='pan_old_bbox_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='pan_pkey')
                    )
    op.drop_constraint('text_with_suggestion_fk', 'suggestions', type_='foreignkey')
    op.drop_table('text_with_suggestions')
    op.add_column('user_position', sa.Column('geocoord_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_position_geocoord_id_fkey', 'user_position', 'geocoordinate_with_time_stamp', ['geocoord_id'], ['id'])
    op.drop_column('user_position', 'time_stamp')
    op.drop_column('user_position', 'geom')
    op.add_column('suggestions', sa.Column('text_with_suggestion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('suggestions_text_with_suggestion_id_fkey', 'suggestions', 'text_with_suggestion', ['text_with_suggestion_id'], ['id'])
    op.drop_column('suggestions', 'text_with_suggestions_id')
    op.add_column('spatial_bookmark', sa.Column('geocoord_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('spatial_bookmark_geocoord_id_fkey', 'spatial_bookmark', 'geocoordinate_with_time_stamp', ['geocoord_id'], ['id'])
    op.drop_column('spatial_bookmark', 'time_stamp')
    op.drop_column('spatial_bookmark', 'geom')
    # op.drop_constraint('origin_text_bbox_fk', 'routing', type_='foreignkey')
    # op.drop_constraint('dest_text_bbox_fk', 'routing', type_='foreignkey')
    op.create_foreign_key('routing_origin_text_box_history_id_fkey', 'routing', 'text_with_suggestion', ['origin_text_box_history_id'], ['id'])
    op.create_foreign_key('routing_destination_text_box_history_id_fkey', 'routing', 'text_with_suggestion', ['destination_text_box_history_id'], ['id'])
    op.add_column('map_search', sa.Column('bbox_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('map_search_bbox_id_fkey', 'map_search', 'bbox', ['bbox_id'], ['id'])
    op.drop_column('map_search', 'bbox_time_stamp')
    op.drop_column('map_search', 'bbox_geom')
    op.add_column('map_interaction', sa.Column('geocoord_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('map_interaction_geocoord_id_fkey', 'map_interaction', 'geocoordinate_with_time_stamp', ['geocoord_id'], ['id'])
    op.drop_column('map_interaction', 'where_clicked_geom')
    op.drop_column('map_interaction', 'time_stamp')
    op.drop_column('map_interaction', 'old_zoom_level')
    op.drop_column('map_interaction', 'old_bbox_time_stamp')
    op.drop_column('map_interaction', 'old_bbox_geom')
    op.drop_column('map_interaction', 'new_zoom_level')
    op.drop_column('map_interaction', 'new_bbox_time_stamp')
    op.drop_column('map_interaction', 'new_bbox_geom')
    op.drop_column('map_interaction', 'is_zoom_out_interaction')
    op.drop_column('map_interaction', 'is_zoom_in_interaction')
    op.drop_column('map_interaction', 'is_pan_interaction')
    op.drop_column('map_interaction', 'is_click_interaction')
    op.drop_column('map_interaction', 'geom')
    op.drop_column('map_interaction', 'click_time_stamp')
    # op.create_index('idx_geocoordinate_with_time_stamp_geom', 'geocoordinate_with_time_stamp', ['geom'], unique=False)
    # ### end Alembic commands ###
