"""empty message

Revision ID: 86697f03e85b
Revises: 6c7b56b35fa5
Create Date: 2019-11-16 00:06:01.590734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86697f03e85b'
down_revision = '6c7b56b35fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    priority = postgresql.ENUM('mapped', 'web', name='sessiontype')
    priority.create(op.get_bind())
    op.add_column('mapped_session', sa.Column('session_type', sa.Enum('mapped', 'web', name='sessiontype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapped_session', 'session_type')
    # ### end Alembic commands ###
