"""minor improvements

Revision ID: ea249d496934
Revises: 2195e3e2a9ce
Create Date: 2019-11-03 15:14:01.717567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'ea249d496934'
down_revision = '2195e3e2a9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_interaction', sa.Column('new_bbox_time_stamp_lr', sa.DateTime(), nullable=True))
    op.add_column('map_interaction', sa.Column('new_bbox_time_stamp_ul', sa.DateTime(), nullable=True))
    op.add_column('map_interaction', sa.Column('old_bbox_time_stamp_lr', sa.DateTime(), nullable=True))
    op.add_column('map_interaction', sa.Column('old_bbox_time_stamp_ul', sa.DateTime(), nullable=True))
    op.drop_column('map_interaction', 'click_time_stamp')
    op.drop_column('map_interaction', 'where_clicked_geom')
    op.drop_column('map_interaction', 'old_bbox_time_stamp')
    op.drop_column('map_interaction', 'new_bbox_time_stamp')
    op.add_column('map_search', sa.Column('bbox_time_stamp_lr', sa.DateTime(), nullable=True))
    op.add_column('map_search', sa.Column('bbox_time_stamp_ul', sa.DateTime(), nullable=True))
    op.alter_column('map_search', 'bbox_geom', nullable=True)
    op.drop_column('map_search', 'bbox_time_stamp')
    op.create_foreign_key('origin_text_box_id_fkey', 'routing', 'text_with_suggestions', ['origin_text_box_history_id'], ['id'])
    op.create_foreign_key('destination_text_box_id_fkey', 'routing', 'text_with_suggestions', ['destination_text_box_history_id'], ['id'])
    op.add_column('text_with_suggestions', sa.Column('suggestion_chosen', sa.Text(), nullable=True))
    op.drop_column('text_with_suggestions', 'suggestion_choosen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_with_suggestions', sa.Column('suggestion_choosen', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('text_with_suggestions', 'suggestion_chosen')
    op.drop_constraint('origin_text_box_id_fkey', 'routing', type_='foreignkey')
    op.drop_constraint('destination_text_box_id_fkey', 'routing', type_='foreignkey')
    op.add_column('map_search', sa.Column('bbox_time_stamp', sa.DateTime(), nullable=False))
    op.drop_column('map_search', 'bbox_time_stamp_lr')
    op.drop_column('map_search', 'bbox_time_stamp_ul')
    op.alter_column('map_search', 'bbox_geom', nullable=False)
    op.add_column('map_interaction', sa.Column('new_bbox_time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('map_interaction', sa.Column('old_bbox_time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('map_interaction', sa.Column('where_clicked_geom', Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True))
    op.add_column('map_interaction', sa.Column('click_time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('map_interaction', 'old_bbox_time_stamp_ul')
    op.drop_column('map_interaction', 'old_bbox_time_stamp_lr')
    op.drop_column('map_interaction', 'new_bbox_time_stamp_ul')
    op.drop_column('map_interaction', 'new_bbox_time_stamp_lr')
    # ### end Alembic commands ###
