"""complete xsd

Revision ID: ed6021c67b9f
Revises:
Create Date: 2019-10-24 12:15:08.223688

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = 'ed6021c67b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoordinate_with_time_stamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapped_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_application_time_stamp', sa.DateTime(), nullable=False),
    sa.Column('end_application_time_stamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upper_left_coordinate_id', sa.Integer(), nullable=True),
    sa.Column('lower_right_coordinate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lower_right_coordinate_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.ForeignKeyConstraint(['upper_left_coordinate_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('geocoord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spatial_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('geocoord_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('geocoord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_interaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_interaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_interaction_id'], ['map_interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('starttime_stamp', sa.DateTime(), nullable=False),
    sa.Column('endtime_stamp', sa.DateTime(), nullable=False),
    sa.Column('bbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bbox_id'], ['bbox.id'], ),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_interaction_type_id', sa.Integer(), nullable=True),
    sa.Column('where_clicked_id', sa.Integer(), nullable=True),
    sa.Column('bbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bbox_id'], ['bbox.id'], ),
    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], ),
    sa.ForeignKeyConstraint(['where_clicked_id'], ['geocoordinate_with_time_stamp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_interaction_type_id', sa.Integer(), nullable=True),
    sa.Column('old_bbox_id', sa.Integer(), nullable=True),
    sa.Column('new_bbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], ),
    sa.ForeignKeyConstraint(['new_bbox_id'], ['bbox.id'], ),
    sa.ForeignKeyConstraint(['old_bbox_id'], ['bbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_with_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_search_id', sa.Integer(), nullable=True),
    sa.Column('text_typed', sa.Text(), nullable=False),
    sa.Column('suggestion_choosen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['map_search_id'], ['map_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoom_in_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_interaction_type_id', sa.Integer(), nullable=True),
    sa.Column('old_zoom_level', sa.Integer(), nullable=False),
    sa.Column('new_zoom_level', sa.Integer(), nullable=False),
    sa.Column('old_bbox_id', sa.Integer(), nullable=True),
    sa.Column('new_bbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_interaction_type_id'], ['map_interaction_type.id'], ),
    sa.ForeignKeyConstraint(['new_bbox_id'], ['bbox.id'], ),
    sa.ForeignKeyConstraint(['old_bbox_id'], ['bbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapped_session_id', sa.Integer(), nullable=True),
    sa.Column('start_routing_interface_time_stamp', sa.DateTime(), nullable=False),
    sa.Column('end_routing_interface_send_request_or_interface_closed_time_stamp', sa.DateTime(), nullable=False),
    sa.Column('start_routing_time_stamp', sa.DateTime(), nullable=True),
    sa.Column('end_routing_time_stamp', sa.DateTime(), nullable=True),
    sa.Column('origin_text_box_history_id', sa.Integer(), nullable=True),
    sa.Column('destination_text_box_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_text_box_history_id'], ['text_with_suggestion.id'], ),
    sa.ForeignKeyConstraint(['mapped_session_id'], ['mapped_session.id'], ),
    sa.ForeignKeyConstraint(['origin_text_box_history_id'], ['text_with_suggestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_with_suggestion_id', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['text_with_suggestion_id'], ['text_with_suggestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('routing')
    op.drop_table('zoom_in_out')
    op.drop_table('text_with_suggestion')
    op.drop_table('pan')
    op.drop_table('click')
    op.drop_table('map_search')
    op.drop_table('map_interaction_type')
    op.drop_table('user_position')
    op.drop_table('spatial_bookmark')
    op.drop_table('question')
    op.drop_table('map_interaction')
    op.drop_table('bbox')
    op.drop_table('mapped_session')
    op.drop_table('geocoordinate_with_time_stamp')
    # ### end Alembic commands ###
